-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.9.0.99.2
-- Module  Version: 3.9
--C:\lscc\diamond\3.9_x64\ispfpga\bin\nt64\scuba.exe -w -n RAM -lang vhdl -synth lse -bus_exp 7 -bb -arch xo2c00 -type sspram -addr_width 3 -num_rows 8 -data_width 16 -outData UNREGISTERED 

-- Thu May 11 23:18:46 2017

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity RAM is
    port (
        Data: in  std_logic_vector(11 downto 0); 
        Clock: in  std_logic; 
        WE: in  std_logic; 
        ClockEn1: in  std_logic;
		ClockEn2: in  std_logic;
        Q: out  std_logic_vector(11 downto 0));
end RAM;

architecture Structure of RAM is

    -- internal signal declarations
    signal dec0_wre3: std_logic;
    signal scuba_vhi: std_logic;
	signal dummy: std_logic;
	
    -- local component declarations
    component ROM16X1A
        generic (INITVAL : in std_logic_vector(15 downto 0));
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component SPR16X4C
        generic (INITVAL : in String);
        port (DI0: in  std_logic; DI1: in  std_logic; DI2: in  std_logic; 
            DI3: in  std_logic; CK: in  std_logic; WRE: in  std_logic; 
            AD0: in  std_logic; AD1: in  std_logic; AD2: in  std_logic; 
            AD3: in  std_logic; DO0: out  std_logic; DO1: out  std_logic; 
            DO2: out  std_logic; DO3: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    attribute MEM_INIT_FILE : string; 
    attribute MEM_LPC_FILE : string; 
    attribute COMP : string; 
    attribute MEM_INIT_FILE of mem_0_0 : label is "(0-7)(0-3)";
    attribute MEM_LPC_FILE of mem_0_0 : label is "RAM.lpc";
    attribute COMP of mem_0_0 : label is "mem_0_0";
    attribute MEM_INIT_FILE of mem_0_1 : label is "(0-7)(4-7)";
    attribute MEM_LPC_FILE of mem_0_1 : label is "RAM.lpc";
    attribute COMP of mem_0_1 : label is "mem_0_1";
    attribute MEM_INIT_FILE of mem_0_2 : label is "(0-7)(8-11)";
    attribute MEM_LPC_FILE of mem_0_2 : label is "RAM.lpc";
    attribute COMP of mem_0_2 : label is "mem_0_2";
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    LUT4_0: ROM16X1A
        generic map (initval=> X"8000")
        port map (AD3=>WE, AD2=>ClockEn1, AD1=>ClockEn2, AD0=>scuba_vhi, 
            DO0=>dec0_wre3);

    mem_0_0: SPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(8), DI1=>Data(9), DI2=>Data(10), 
            DI3=>Data(11), CK=>Clock, WRE=>dec0_wre3, AD0=>scuba_vhi, 
            AD1=>scuba_vhi, AD2=>scuba_vhi, AD3=>scuba_vhi, DO0=>Q(8), 
            DO1=>Q(9), DO2=>Q(10), DO3=>Q(11));

    mem_0_1: SPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(4), DI1=>Data(5), DI2=>Data(6), 
            DI3=>Data(7), CK=>Clock, WRE=>dec0_wre3, AD0=>scuba_vhi, 
            AD1=>scuba_vhi, AD2=>scuba_vhi, AD3=>scuba_vhi, DO0=>Q(4), 
            DO1=>Q(5), DO2=>Q(6), DO3=>Q(7));

    mem_0_2: SPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(0), DI1=>Data(1), DI2=>Data(2), 
			DI3=>Data(3), CK=>Clock, WRE=>dec0_wre3, AD0=>scuba_vhi, 
			AD1=>scuba_vhi, AD2=>scuba_vhi, AD3=>scuba_vhi, DO0=>Q(0), DO1=>Q(1), 
            DO2=>Q(2), DO3=>Q(3));

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of RAM is
    for Structure
        for all:ROM16X1A use entity MACHXO2.ROM16X1A(V); end for;
        for all:SPR16X4C use entity MACHXO2.SPR16X4C(V); end for;
        for all:VHI use entity MACHXO2.VHI(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
